// <auto-generated />
using System;
using ForestInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForestInventory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116234528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForestInventory.Domain.Entities.Arbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Altitud")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("Altura")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("AlturaComercial")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Dap")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("DiametroCopa")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaMedicion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ParcelaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Sincronizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SyncId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCreadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("ParcelaId", "Codigo")
                        .IsUnique();

                    b.ToTable("Arboles");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("DensidadMadera")
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Familia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCientifico")
                        .IsUnique();

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("Altitud")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("Area")
                        .HasPrecision(10, 4)
                        .HasColumnType("double precision");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioCreadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detalles")
                        .HasColumnType("text");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text");

                    b.Property<int>("RegistrosEnviados")
                        .HasColumnType("integer");

                    b.Property<int>("RegistrosRecibidos")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Organizacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Arbol", b =>
                {
                    b.HasOne("ForestInventory.Domain.Entities.Especie", "Especie")
                        .WithMany("Arboles")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForestInventory.Domain.Entities.Parcela", "Parcela")
                        .WithMany("Arboles")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForestInventory.Domain.Entities.Usuario", "UsuarioCreador")
                        .WithMany("Arboles")
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Parcela");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("ForestInventory.Domain.Entities.Usuario", "UsuarioCreador")
                        .WithMany("Parcelas")
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.SyncLog", b =>
                {
                    b.HasOne("ForestInventory.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Especie", b =>
                {
                    b.Navigation("Arboles");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Parcela", b =>
                {
                    b.Navigation("Arboles");
                });

            modelBuilder.Entity("ForestInventory.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Arboles");

                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
